Vagrant.configure("2") do |config|
    config.vm.box = "jacobw/fedora35-arm64"
    # config.vm.network :private_network, ip: "192.168.56.88"
    config.vm.network "public_network", ip: "192.168.56.88"
    config.vm.provider "vmware_desktop" do |v|
        v.gui = true
        v.memory = "1024"
    end
    config.vm.provision "shell", inline: <<-SHELL
    yum install httpd wget unzip vim -y
    systemctl start httpd
    systemctl enabled httpd
    mkdir -p /tmp/website
    cd /tmp/website
    wget https://www.tooplate.com/zip-templates/2134_gotto_job.zip
    unzip -o 2134_gotto_job.zip
    cp -r 2134_gotto_job/* /var/www/html/
    systemctl restart httpd
    cd /tmp/
    rm -rf /tmp/website
  SHELL
end
